spring:
  kafka:
    properties:
      bootstrap:
        servers: localhost:9092
      security:
        protocol: PLAINTEXT


schema.registry.url: http://localhost:8081
schema.registry.user_info: "foo:bar"
